version: '3.8'

services:
  frontend-public:
    build: 
      context: ./frontend-public
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://agricalendar.net/api
    restart: unless-stopped
    depends_on:
      - backend

  frontend-admin:
    build: 
      context: ./frontend-admin
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://agricalendar.net/api
      - NEXT_PUBLIC_BASE_PATH=/admin
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@postgres:5432/agricalendar
      - JWT_SECRET=your-super-secret-jwt-key
      - PORT=5000
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=agricalendar
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=your-secure-password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

volumes:
  postgres_data:
